apiVersion: v2
name: elasticsearch-operator
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.0"
dependencies:
  - name: test-elastic
    version: 0.7.0
    repository: https://csantanapr.github.io/toolkit-charts