apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch
spec:
  destination:
    namespace: tools
    server: 'https://kubernetes.default.svc'
  project: services
  source:
    path: 2-services/elasticsearch
    repoURL: https://github.com/csantanapr-cn-toolkit-tests/gitops-03-18.git
    targetRevision: main
    helm:
      valueFiles: []
  syncPolicy:
    automated:
      prune: true
      selfHeal: true