apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jaeger
spec:
  destination:
    namespace: openshift-operators
    server: 'https://kubernetes.default.svc'
  project: services
  source:
    path: 2-services/jaeger
    repoURL: https://github.com/csantanapr-cn-toolkit-tests/gitops-03-18.git
    targetRevision: main
    helm: {}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true